spring:
    application:
        name: @project.name@
        version: @project.version@
    datasource:
        url: jdbc:postgresql://localhost:5432/ridepally
        username:
        password:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

app:
    jwt:
        # Use a strong secret key in production
        secret: ridepallyTest4968254680SecureSecretKeyForJwtAuthenticationAndAuthorization
        expirationMs: 3600000      # 1 hour
        refreshExpirationMs: 86400000   # 24 hours
    nonce:
        expirationMs: 86400000   #24 hours